### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by r0fls**
typo

### CODE REVIEW

**Comment by danhardman** [comment]
You've made a typo of your own...

```
result := n.Caculate([]float64{0,1,0,1,1,1,0,1,0})
```

Should be

```
result := n.Calculate([]float64{0,1,0,1,1,1,0,1,0})
```

**Comment by r0fls** [comment]
Well how bout that... Fixed it!

**Comment by danhardman** [comment]
Pretty sure the author has abandoned this repo. Haven't heard from him in a month

**Comment by NOX73** [comment]
Let's do it :D

@danhardman, @r0fls guys, could you tell me where do you use this lib? I wrote it just for self education and could not imagine that someone would use it )))

**Comment by danhardman** [comment]
@NOX73 I'm using it to create a smart thermostat like Hive or Nest that predicts the time it takes to heat a space. Final year project for my dissertation!

**Pull request merged**
